### PR TITLE
fix(test): Ignore system indices in ES rollover integration test

### LINKED ISSUE #8908: [Bug]: Flaky OpenSearch e2e, index rollover test's IndexNames() assertion leaks system `top_queries-*` indices (follow-up to #7002)
### What happened?

The OpenSearch index-rollover integration test intermittently fails even when nothing is functionally wrong. The test asserts exact set-equality between every index present on the cluster and the list of Jaeger indices it expects to have created. OpenSearch's Query Insights plugin asynchronously creates system indices named `top_queries-YYYY.MM.DD-*`. Whenever one of those happens to exist during the test window, it appears in the actual index list but not in the expected list, so the assertion fails spuriously.

This is the exact same flake that #7002 reported and fixed, but the fix was only applied to the **index cleaner** test. The **index rollover** test contains the identical unfiltered assertion and was never updated, so the flake still lives there.

### Steps to reproduce

1. This is inherently timing-dependent (flaky), like #7002, it fails only when a `top_queries-*` system index exists while the rollover test lists indices.
2. To demonstrate the gap deterministically: create any non-Jaeger index (e.g. `top_queries-2026.07.01-00001`) on the OpenSearch cluster before the rollover test calls `client.IndexNames()`, then run the OpenSearch rollover integration test. The assertion at `internal/storage/integration/es_index_rollover_test.go:154` fails because the extra index is in "actual" but not "expected".

### Expected behavior

The rollover test should ignore non-Jaeger / system indices when verifying the indices it created, exactly as the cleaner test already does, so unrelated plugin/system indices (`top_queries-*`, etc.) don't cause spurious failures. The assertion should still be a strict exact-match over the *Jaeger* indices (no weakening).

### Relevant log output

```shell
es_index_rollover_test.go:154:
        Error Trace: internal/storage/integration/es_index_rollover_test.go:154
        Error:       elements differ
                     extra elements in list A:
                     ([]string) (len=1) {
                      (string) "top_queries-2026.07.01-44476"
                     }
        Test:        TestIndexRollover_CreateIndicesWithILM
```

### Screenshot

N/A... see #7002 for the analogous cleaner-test failure with `top_queries-2025.04.08-51429`.

### Additional context

Root cause is a missed call site from the #7002 fix. The cleaner test filters system indices before comparing:

```go
// internal/storage/integration/es_index_cleaner_test.go
for _, index := range foundIndices {
    // ignore system indices https://github.com/jaegertracing/jaeger/issues/7002
    if strings.HasPrefix(index, prefix+"jaeger") {
        actual = append(actual, index)
    }
}
assert.ElementsMatch(t, actual, expected, ...)
```

The rollover test does not, it passes the raw `IndexNames()` straight into the assertion:

```go
// internal/storage/integration/es_index_rollover_test.go:139,154
indices, err := client.IndexNames()
...
assert.ElementsMatch(t, indices, expected)
```

Proposed fix: apply the same `strings.HasPrefix(index, prefix+"jaeger")` filter used in the cleaner test before the `ElementsMatch` in the rollover test. This is non-breaking (on a clean cluster the filtered set equals the full set) and does not weaken the assertion (still exact-match over Jaeger indices).

### Jaeger backend version

Reproducible on current `main` (test-only; not version-specific).

### SDK

N/A... internal integration test, no client SDK involved.

### Pipeline

N/A... storage integration test harness.

### Stogage backend

OpenSearch (Elasticsearch/OpenSearch storage integration suite).

### Operating system

Linux (GitHub Actions CI); not OS-specific.

### Deployment model

N/A... CI integration test against a containerized OpenSearch instance.

### Deployment configs

```shell
N/A
```

### PR DESCRIPTION
**Pull request by Me-Priyank**
## Which problem is this PR solving?
- Resolves #8908
- Follow-up to #7002, the same system-index flake, at a call site that fix missed.

## Description of the changes
- The OpenSearch/ES index **rollover** integration test asserted exact set-equality between *every* index returned by `client.IndexNames()` and the expected Jaeger indices. On OpenSearch, the Query Insights plugin asynchronously creates system indices (`top_queries-*`) that leak into the assertion and cause spurious failures.
- The index **cleaner** test already filters these out (#7002). This PR applies the same `strings.HasPrefix(index, prefix+"jaeger")` filter in the rollover test before `assert.ElementsMatch`, so only Jaeger-owned indices are compared.
- The assertion stays a strict exact-match over Jaeger indices (**not** weakened); on a clean cluster the filtered set equals the full set, so behavior is unchanged.
- Scope note: `TestIndexRollover_FailIfILMNotPresent` has the same `assert.Empty(indices)` pattern on raw `IndexNames()` (line 43) and is theoretically vulnerable to the same leak. I kept this PR scoped to the `ElementsMatch` case from #7002's lineage; happy to fold it in or file a follow-up if preferred.

## How was this change tested?
- `gofmt`, `go vet ./internal/storage/integration/`, and repo-pinned `golangci-lint run ./internal/storage/integration/` all pass (0 issues).
- The rollover integration test is gated by `SkipUnlessEnv(StorageElasticsearch, StorageOpenSearch)` and requires a live cluster, so it exercises in the ES/OpenSearch e2e CI jobs rather than locally. The change is a verbatim mirror of the merged #7002 filter, and `prefix+"jaeger"` matches every expected index, so no legitimate Jaeger index is dropped.

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality 
- [x] I have run lint and test steps successfully: `make lint test`

## AI Usage in this PR (choose one)

- [x] **None**: No AI tools were used in creating this PR

### CODE REVIEW

File: internal/storage/integration/es_index_rollover_test.go [hunk 1]
```diff
@@ -150,8 +150,15 @@ func runIndexRolloverWithILMTest(t *testing.T, client *elastic.Client, version e
 			actualWriteAliases = append(actualWriteAliases, v.Settings["index.lifecycle.rollover_alias"].(string))
 		}
 	}
+	// ignore system indices https://github.com/jaegertracing/jaeger/issues/7002
```
Comment (yurishkuro) [inline internal/storage/integration/es_index_rollover_test.go]: this should be done right after L140. But a better fix is to only query for the desired indices in the first place. Why possible reason do we have for a function like this that reads "all indices in the cluster"?
```
// IndexNames returns the names of all indices in the cluster.
func (c *Client) IndexNames() ([]string, error) {
```

Comment (yurishkuro) [reply internal/storage/integration/es_index_rollover_test.go]: and perhaps it would also help the index cleaner

Comment (Me-Priyank) [reply internal/storage/integration/es_index_rollover_test.go]: Done @yurishkuro ... Switched from listing all cluster indices and filtering to querying the `jaeger-*` pattern directly via a small `getJaegerIndices` helper, so unrelated system indices (e.g. `top_queries-*`) never enter the result in the first place. This mirrors how the rollover client itself scopes lookups (`GetJaegerIndices`).

Applied it to the index cleaner too, as you suggested, its `IndexNames()` + filter is replaced by the same helper. It also removes the same latent flake from `TestIndexRollover_FailIfILMNotPresent`, which previously asserted `Empty` against every index in the cluster.

File: internal/storage/integration/es_index_rollover_test.go [hunk 2]
```diff
@@ -169,6 +164,21 @@ func getBackendVersion(client *elastic.Client) (es.BackendVersion, error) {
...
+// tests do not need to filter them out. See #7002.
+func getJaegerIndices(t *testing.T, client *elastic.Client, prefix string) []string {
+	settings, err := client.IndexGetSettings(prefix + "jaeger-*").Do(context.Background())
+	require.NoError(t, err)
+	indices := make([]string, 0, len(settings))
+	for name := range settings {
+		indices = append(indices, name)
+	}
+	return indices
+}
```
[the remark this answers is not in the document]
Comment (Me-Priyank) [reply internal/storage/integration/es_index_rollover_test.go:166]: `jaeger-*` is a wildcard expression, and `_settings` requests honor `allow_no_indices` (default `true`), so a no-match returns `200 {}`, not a 404, a 404 only occurs for a concrete index name. Note this is the same behavior `IndexNames()` itself relies on: it's `IndexGetSettings().Index("_all")` under the hood, and `_all` on an empty cluster returns empty for the same reason. So there's no regression here, and `TestIndexRollover_FailIfILMNotPresent` gets its expected empty result.

**Comment by Me-Priyank** [comment]
@yurishkuro PTAL

**Comment by Me-Priyank** [comment]
Closing this as obsolete: the system-index filtering it adds is already in `main`.

`esTestClient.jaegerIndexNames` calls `esclient.GetJaegerIndices`, which queries `prefix + "jaeger-*"` directly ([index_client.go#L67](https://github.com/jaegertracing/jaeger/blob/main/internal/storage/elasticsearch/esclient/index_client.go#L67)), so unrelated indices such as OpenSearch's `top_queries-*` never enter the result. `es_index_cleaner_test.go` already documents this against #7002.

This branch predates the esclient migration of these integration tests, so merging `main` produced a semantic conflict rather than a textual one. The merged file reintroduces the olivere `elastic.Client` helpers that the migration replaced (`cleanES`, `createILMPolicy`, `getBackendVersion`, `getJaegerIndices`) while taking `main`'s slimmed imports, which is why lint now fails with `undefined: elastic, context, strings, strconv, fmt`.
